# Generated by Django 4.2.7 on 2023-11-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_catalog_description_catalog_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='photo',
            field=models.ImageField(default='shop\\main\templates\\main\\media\\empty.png', upload_to='photo/%Y/%m/%d/', verbose_name='Image of product'),
        ),
    ]
